package com.chenbaiyu.dao.cargo;

import com.chenbaiyu.domain.cargo.Factory;
import com.chenbaiyu.domain.cargo.FactoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FactoryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    long countByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int deleteByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int insert(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int insertSelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    List<Factory> selectByExample(FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    Factory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Factory record, @Param("example") FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Factory record, @Param("example") FactoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Factory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_factory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Factory record);
}